### ISSUE TITLE
Create pick-up/drop-off points and let commuters select their pick-up/drop-off points

### ISSUE THREAD

**Issue by chico000** [flairekq/OOPP-waffle#1]
As a commuter, I wish to be able to select the pick-up point and drop-off point so that I will be able to indicate my interest in the route that I want.

**Comment by thedud1** [comment]
hahahah

**Comment by chico000** [comment]
Acceptance criteria: 
1. Mark all the pick-up/drop-off points
2. Allow commuters to select the pick-up and drop-off point they want and record in the database
